services:
  nginx:
    ports:
      - "5000:80"

  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development

    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist

    env_file:
        - .env
    environment:
      - NODE_ENV=development
    
    command: npm run dev

  mongo:
    image: mongo

    volumes:
      - mongo-db:/data/db #named volumes with name mongo-db


  redis:
    image: redis

networks:
  my_network:
    driver: bridge
