services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx configuration
      - ./public:/usr/share/nginx/html        # Serve static files (if required)
    ports:
      - "5000:80"                             # Expose port 80 from the container to 5000 on the host
    depends_on:
      - node-app                         # Wait for the ecommerce app to be ready
    networks:
      - my_network

  node-app:
    build: .                                  # Build the image from the current directory
    container_name: node-app
    volumes:
      - .:/app                               # Mount the project directory for development
      - /app/node_modules                    # Persistent volume for `node_modules`
      - /app/dist                            # Persistent volume for `dist` directory
    environment:
      - PORT=5000                            # Set the app's listening port
    depends_on:
      - mongo                                # Ensure MongoDB is up before starting
    networks:
      - my_network

  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - .env                          # Load environment variables from `.env`
    volumes:
      - mongo-db:/data/db                    # Persistent named volume for MongoDB
    networks:
      - my_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"                          # Optional: Expose Redis for debugging or external access
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongo-db:
    driver: local                            # Ensure the volume uses the default local driver
